### ISSUE TITLE
`text-box-trim` and `text-box-edge` in Canary behind a flag 

### ISSUE THREAD

**Issue by argyleink** [KyleAMathews/vite-plugin-capsize-radix-ui#2]
```css
h1 {
  text-box-trim: both;
  text-box-edge: ex alphabetic;
```

<img width="787" alt="Screenshot 2024-06-10 at 1 35 14 PM" src="https://github.com/KyleAMathews/vite-plugin-capsize-radix-ui/assets/1134620/527653f7-9d78-458c-938c-4696cd3fd132">

Would love to capture feedback from experiments you do. [Spec for ref](https://drafts.csswg.org/css-inline-3/#leading-trim).

**Comment by KyleAMathews** [comment]
Exciting!

Is there a capsize issue? I think this plugin would want to wait for capsize to implement support as it's a pretty thin wrapper around capsize.

**Comment by argyleink** [comment]
oh poo, good call, i'll go share it there instead
